name: Daily Empty Commit

on:
  schedule:
    # Runs every day at a specific time (e.g., 5:30 UTC)
    - cron: '30 5 * * *'
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  daily_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Create empty commit and push
        run: |
          git commit --allow-empty -m "Automated daily commit to track activity"
          git push
